// frontend-react/src/pages/Dashboard.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useAuth } from '../context/AuthContext';
import { useTranslation } from 'react-i18next';
import { Wallet, TrendingDown, TrendingUp } from 'lucide-react';
import UfoWelcome from '../components/UfoWelcome';
import './Dashboard.css';

interface Transaction {
  id: number;
  amount: number;
  type: 'expense' | 'income';
}

const Dashboard: React.FC = () => {
  const { axiosInstance } = useAuth();
  const { t } = useTranslation();
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchData = useCallback(async () => {
    try {
      const response = await axiosInstance.get('/transactions');
      const data = response.data.transactions || response.data;
      setTransactions(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error('Error loading transactions:', err);
    } finally {
      setLoading(false);
    }
  }, [axiosInstance]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const totalIncome = transactions.filter(t => t.type === 'income').reduce((acc, t) => acc + Number(t.amount), 0);
  const totalExpense = transactions.filter(t => t.type === 'expense').reduce((acc, t) => acc + Number(t.amount), 0);
  const balance = totalIncome - totalExpense;

  if (loading) return <div className="dashboard-wrapper">{t('dashboard.loading')}</div>;

  return (
    <div className="dashboard-wrapper">
      <h1 className="dashboard-title">{t('dashboard.title')}</h1>

      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-icon wallet"><Wallet size={24}/></div>
          <div className="stat-content">
            <p className="label">{t('dashboard.balance')}</p>
            <p className="value">${balance.toLocaleString()}</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon income"><TrendingUp size={24}/></div>
          <div className="stat-content">
            <p className="label">{t('dashboard.income')}</p>
            <p className="value-plus">+${totalIncome.toLocaleString()}</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon expense"><TrendingDown size={24}/></div>
          <div className="stat-content">
            <p className="label">{t('dashboard.expenses')}</p>
            <p className="value-minus">-${totalExpense.toLocaleString()}</p>
          </div>
        </div>
      </div>

      <UfoWelcome />
    </div>
  );
};

export default Dashboard;

// frontend-angular/src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit, signal, computed } from '@angular/core';
import { TranslateModule } from '@ngx-translate/core';
import { TransactionService } from '../../services/transaction.service';
import { type Transaction } from '../../models/transaction.model';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [TranslateModule],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.css'
})
export class DashboardComponent implements OnInit {
  transactions = signal<Transaction[]>([]);
  loading = signal(true);

  totalIncome = computed(() =>
    this.transactions().filter(t => t.type === 'income').reduce((acc, t) => acc + Number(t.amount), 0)
  );

  totalExpense = computed(() =>
    this.transactions().filter(t => t.type === 'expense').reduce((acc, t) => acc + Number(t.amount), 0)
  );

  balance = computed(() => this.totalIncome() - this.totalExpense());

  constructor(private transactionService: TransactionService) {}

  ngOnInit(): void {
    this.transactionService.getTransactions().subscribe({
      next: (res) => {
        this.transactions.set(res.transactions || []);
        this.loading.set(false);
      },
      error: () => this.loading.set(false)
    });
  }

  formatAmount(n: number): string {
    return n.toLocaleString();
  }
}

<div class="dashboard-wrapper">
  @if (loading()) {
    <div>{{ 'dashboard.loading' | translate }}</div>
  } @else {
    <h1 class="dashboard-title">{{ 'dashboard.title' | translate }}</h1>

    <div class="stats-grid">
      <div class="stat-card">
        <div class="stat-icon wallet">💰</div>
        <div class="stat-content">
          <p class="label">{{ 'dashboard.balance' | translate }}</p>
          <p class="value">${{ formatAmount(balance()) }}</p>
        </div>
      </div>

      <div class="stat-card">
        <div class="stat-icon income">📈</div>
        <div class="stat-content">
          <p class="label">{{ 'dashboard.income' | translate }}</p>
          <p class="value-plus">+${{ formatAmount(totalIncome()) }}</p>
        </div>
      </div>

      <div class="stat-card">
        <div class="stat-icon expense">📉</div>
        <div class="stat-content">
          <p class="label">{{ 'dashboard.expenses' | translate }}</p>
          <p class="value-minus">-${{ formatAmount(totalExpense()) }}</p>
        </div>
      </div>
    </div>

    <div class="welcome-card">
      <h2>{{ 'dashboard.welcome_title' | translate }}</h2>
      <p>{{ 'dashboard.welcome_body' | translate }}</p>
    </div>
  }
</div>
