// frontend-angular/src/app/components/layout/layout.component.ts
import { Component, inject } from '@angular/core';
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';
import { TranslateModule } from '@ngx-translate/core';
import { AuthService } from '../../services/auth.service';
import { ThemeService } from '../../services/theme.service';
import { LanguageSwitcherComponent } from '../language-switcher/language-switcher.component';
import { Router } from '@angular/router';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive, TranslateModule, LanguageSwitcherComponent],
  templateUrl: './layout.component.html',
  styleUrl: './layout.component.css'
})
export class LayoutComponent {
  auth = inject(AuthService);
  theme = inject(ThemeService);
  router = inject(Router);

  get username(): string | null {
    return this.auth.getUsername();
  }

  get isDark(): boolean {
    return this.theme.isDark();
  }

  toggleTheme(): void {
    this.theme.toggle();
  }

  logout(): void {
    this.auth.logout();
    this.router.navigate(['/login']);
  }
}

<div class="app-container">
  <aside class="sidebar">
    <div class="sidebar-logo">{{ 'nav.app_title' | translate }}</div>

    <nav class="nav-links">
      <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}" class="nav-item">
        {{ 'nav.home' | translate }}
      </a>
      <a routerLink="/categories" routerLinkActive="active" class="nav-item">
        {{ 'nav.categories' | translate }}
      </a>
      <a routerLink="/transactions" routerLinkActive="active" class="nav-item">
        {{ 'nav.transactions' | translate }}
      </a>
      <a routerLink="/statistics" routerLinkActive="active" class="nav-item">
        {{ 'nav.statistics' | translate }}
      </a>
    </nav>

    <app-language-switcher />

    <button class="theme-toggle-btn" (click)="toggleTheme()" [title]="(isDark ? 'theme.toggle_light' : 'theme.toggle_dark') | translate">
      <span>{{ isDark ? '☀' : '🌙' }}</span>
      {{ (isDark ? 'theme.toggle_light' : 'theme.toggle_dark') | translate }}
    </button>

    <div class="user-info">
      <span class="user-info-label">{{ 'nav.user_label' | translate }}</span>
      <span class="user-info-name">{{ username }}</span>
    </div>

    <button class="logout-button" (click)="logout()">
      {{ 'nav.logout' | translate }}
    </button>
  </aside>

  <main class="main-content">
    <router-outlet />
  </main>
</div>

// frontend-react/src/components/Layout.tsx
import React from 'react';
import { NavLink, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useTranslation } from 'react-i18next';
import LanguageSwitcher from './LanguageSwitcher';
import './Layout.css';

const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { logout, user } = useAuth();
  const { t } = useTranslation();
  const navigate = useNavigate();

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  return (
    <div className="app-container">
      <aside className="sidebar">
        <div className="sidebar-logo">{t('nav.app_title')}</div>

        <nav className="nav-links">
          <NavLink to="/" className="nav-item" end>{t('nav.home')}</NavLink>
          <NavLink to="/categories" className="nav-item">{t('nav.categories')}</NavLink>
          <NavLink to="/transactions" className="nav-item">{t('nav.transactions')}</NavLink>
          <NavLink to="/statistics" className="nav-item">{t('nav.statistics')}</NavLink>
        </nav>

        <LanguageSwitcher />

        <div className="user-info">
          <span className="user-info-label">{t('nav.user_label')}</span>
          <span className="user-info-name">{user?.username}</span>
        </div>

        <button onClick={handleLogout} className="logout-button">
          {t('nav.logout')}
        </button>
      </aside>

      <main className="main-content">
        {children}
      </main>
    </div>
  );
};

export default Layout;
