// frontend-react/src/pages/Login.tsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useTranslation } from 'react-i18next';
import './Login.css';

interface AxiosErrorResponse {
  response?: {
    data?: {
      error?: string;
    };
  };
}

const Login: React.FC = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const { login, axiosInstance } = useAuth();
  const { t } = useTranslation();
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    try {
      const response = await axiosInstance.post('/login', { username, password });
      const token = response.data.token;
      const tempUserId = 1;
      login(token, username, tempUserId);
      navigate('/', { replace: true });
    } catch (err) {
      console.error("Login failed:", err);
      let errorMessage = t('auth.login_error');
      if (typeof err === 'object' && err !== null && 'response' in err) {
        const axiosError = err as AxiosErrorResponse;
        errorMessage = axiosError.response?.data?.error || errorMessage;
      }
      setError(errorMessage);
    }
  };

  return (
    <div className="auth-page">
      <div className="auth-card">
        <h2 className="auth-title">{t('auth.login_title')}</h2>

        {error && (
          <div className="auth-error" role="alert">
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="auth-form">
          <div className="auth-field">
            <label className="auth-label" htmlFor="username">{t('auth.username')}</label>
            <input
              className="auth-input"
              id="username"
              type="text"
              placeholder={t('auth.username_ph')}
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
            />
          </div>

          <div className="auth-field">
            <label className="auth-label" htmlFor="password">{t('auth.password')}</label>
            <input
              className="auth-input"
              id="password"
              type="password"
              placeholder={t('auth.password_ph')}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </div>

          <button type="submit" className="auth-submit-button">
            {t('auth.login_btn')}
          </button>
        </form>

        <div className="auth-footer">
          <Link to="/register" className="auth-link">
            {t('auth.no_account')}
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Login;

// frontend-angular/src/app/pages/login/login.component.ts
import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { TranslateModule } from '@ngx-translate/core';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [FormsModule, RouterLink, TranslateModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  username = '';
  password = '';
  error = signal('');

  constructor(private auth: AuthService, private router: Router) {}

  onSubmit(): void {
    this.error.set('');
    this.auth.login(this.username, this.password).subscribe({
      next: (res) => {
        this.auth.saveToken(res.token, this.username);
        this.router.navigate(['/']);
      },
      error: () => {
        this.error.set('auth.login_error');
      }
    });
  }
}

<div class="auth-page">
  <div class="auth-card">
    <h2 class="auth-title">{{ 'auth.login_title' | translate }}</h2>

    @if (error()) {
      <div class="auth-error" role="alert">{{ error() | translate }}</div>
    }

    <form class="auth-form" (ngSubmit)="onSubmit()">
      <div class="auth-field">
        <label class="auth-label" for="username">{{ 'auth.username' | translate }}</label>
        <input
          class="auth-input"
          id="username"
          type="text"
          [placeholder]="'auth.username_ph' | translate"
          [(ngModel)]="username"
          name="username"
          required
        />
      </div>

      <div class="auth-field">
        <label class="auth-label" for="password">{{ 'auth.password' | translate }}</label>
        <input
          class="auth-input"
          id="password"
          type="password"
          [placeholder]="'auth.password_ph' | translate"
          [(ngModel)]="password"
          name="password"
          required
        />
      </div>

      <button type="submit" class="auth-submit-button">{{ 'auth.login_btn' | translate }}</button>
    </form>

    <div class="auth-footer">
      <a routerLink="/register" class="auth-link">{{ 'auth.no_account' | translate }}</a>
    </div>
  </div>
</div>
